// <auto-generated />
using LiveFactory.Web.Common;
using LiveFactory.Web.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LiveFactory.Web.Migrations
{
    [DbContext(typeof(LiveDbContext))]
    [Migration("20180428012224_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LiveFactory.Web.Domain.LiveChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image")
                        .HasMaxLength(513);

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("Url")
                        .HasMaxLength(513);

                    b.Property<int>("VideoType")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.ToTable("LiveChannels");
                });

            modelBuilder.Entity("LiveFactory.Web.Domain.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .HasMaxLength(256);

                    b.Property<bool>("IsDisabled")
                        .HasMaxLength(128);

                    b.Property<string>("LastIP")
                        .HasMaxLength(513);

                    b.Property<DateTime>("LastTime")
                        .HasMaxLength(256);

                    b.Property<string>("Password")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
